import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.sass'
import Layout from '../component/Layout'

import { motion , AnimatePresence} from 'framer-motion'




export default function Home() {
  
  const container = {
    hidden: { opacity: 0 , x: -200 , y: 0 },
    show: {
      opacity: 1, x: 0, y: 0,
      transition: {
        staggerChildren: 1
      }
    }
  }
  
  const item = {
    hidden: { opacity: 0 ,  x: -200 , y: 0 },
    show: { opacity: 1  , x: 0 , y: 0}
  } 



  return (
    <>
    <motion.div
      variants={container}
      initial="hidden"
      animate="show"
     className={styles.homeWrap}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.hello} variants={item} > 

      <h1 className={styles.front}>HELLO !</h1>
      <h1 className={styles.back}>HALLO !</h1>

      </section>

      <span className={styles.name} variants={item} >
        
          <p className={styles.first} >I&apos;m</p> 
      
            <p className={styles.inner} >
              <span className={styles.text}>anish kanna</span>
            </p>
            
            
      </span>




    </motion.div>
    </>
  )

}
