import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.sass'
import Layout from '../component/Layout'

import { useRef , useEffect } from 'react'

import Typed from 'typed.js'

import { motion , AnimatePresence} from 'framer-motion'





export default function Home() {

  const el = useRef(null);


  useEffect(() => {
    const typed = new Typed(el.current, {
      strings: [ 'anish' , 'kanna'  ] , 
      startDelay: 500,
      typeSpeed: 200,
      backSpeed: 100,
      backDelay: 1200,
      showCursor: false,
      smartBackspace: true,
      loop: true
    });

    // Destropying
    return () => {
      typed.destroy();
    };
  }, []);


  const skill = [ 'Developer: '  , 'FRONTEND' , 'UI|UX' , 'INTERACTIVE'  ]

  const container = {
    hidden: { opacity: 0 , x: -200 , y: 0 },
    show: {
      opacity: 1, x: 0, y: 0,
      transition: {
        staggerChildren: 1
      }
    }
  }

  const item = {
    hidden: { opacity: 0 ,  x: -200 , y: 0 },
    show: { opacity: 1  , x: 0 , y: 0}
  } 



  return (
    
      <motion.div
        variants={container}
        initial="hidden"
        animate="show"
        className={styles.homeWrap}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

       


        <section className={styles.hello} variants={item} > 

          <h1 className={styles.front}>HELLO !</h1>
          <h1 className={styles.back}>HALLO !</h1>

        </section>

        <div className={styles.name} variants={item} >

          <p className={styles.first} >I&apos;m</p> 

          <p ref={el} className={styles.inner}></p>
        </div>

        <section className = {styles.car} >

          {skill.map((item , index) => (

          <h2 className={styles.skillInner} key={index}  > {item} </h2>

            ))}

        </section>


      </motion.div>
    
  )

}
