import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.sass'
import Layout from '../component/Layout'
export default function Home() {
  return (
    <Layout>
    <div className={styles.homeWrap}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>

    </Layout>
  )

}
