import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Typed from 'react-typed'
import NavBar from '../components/NavBar'

const Home: NextPage = () => {
  
  const skills:any[] = ['frontend' , 'UI|UX' , 'micro-interaction', 'webgl']

  return (

   

    <div className='
        overflow-hidden
        text-zinc-400 bg-zinc-800 font-vonique
        min-h-screen min-w-full flex flex-col items-center justify-between'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className='
          px-5
          flex grow w-full bg-zinc-900  flex-col relative items-start justify-evenly'
        >      
        <section className=' 
         flex items-center justify-end absolute  
          top-0 right-0  '>  
           <NavBar />
      </section>
      <h2 className='
            will-change-transform
            tracking-widest
            book relative rounded-2xl w-[45vmin] lg:w-[55vmin] h-[15vmin] bg-stone-800 flex items-center justify-center' >
          <span className='front absolute' >HELLO !</span>
          <span className='back absolute'>HALLO !</span>
        </h2>  
      <h1 className='w-[100vmin] typed  tracking-wide' >   
        <Typed strings={['I&apos;m anish' , 'I&apos;m kanna' , 'Ich bin anish' , 'Ich bin kanna']}
            smartBackspace={true}  startDelay={2000}
            typeSpeed={120} loop backSpeed={50}/>
        </h1>
      
      </div>

      <section className='
        
        bg-neutral-500 text-zinc-900 
          items-center justify-center flex gap-10' >
       {skills.map(skill=>(
          <h1 key={skill} className='w-fit px-[5vmin] whitespace-nowrap scrollCar' >{skill}</h1>
       ))}  
      </section>  

   </div>
  )
}

export default Home
